spring:
  datasource:
    url: ${URL_BANCO:jdbc:postgresql://localhost:5432/clinicaqr}
    username: ${USUARIO_BANCO:postgres}
    password: ${SENHA_BANCO:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
server:
  port: 8080
aplicacao:
  url-base-publica: ${URL_PUBLICA:http://localhost:5173}
  jwt:
    chave: ${CHAVE_JWT:troque-esta-chave-em-producao-minimo-32-caracteres}
    duracao-ms: 86400000
